name: tankerpcmc
description: A new Flutter project.
publish_to: 'none'


version: 1.0.4+6

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_map: ^3.1.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  syncfusion_flutter_xlsio: ^22.1.37
  flutter_datetime_picker_plus: ^2.0.0+1
  google_map_polyline_new: ^0.3.0+2
  google_maps_flutter: ^2.2.5
  google_maps_flutter_android: ^2.4.10
  google_maps_flutter_platform_interface: ^2.2.1
  google_maps_webservice: ^0.0.19
  http: ^0.13.5
  intl: ^0.18.0
  location: ^4.4.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  shimmer: ^2.0.0
  permission_handler: ^10.2.0
  image: ^4.0.17
  excel: ^2.1.0
  image_gallery_saver: ^2.0.1
  multiselect: ^0.1.0
  flutter_typeahead: ^4.6.1
  in_app_update: ^4.0.1
  csv: ^5.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.12.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/TWRRS.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
